-- Create the users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  twitter_handle text unique not null,
  burner_address text unique not null,
  ethos_score int default 0
);

-- Enable Row Level Security (RLS)
alter table users enable row level security;

-- Create a policy that allows the service role (backend) to do anything
-- Note: You need to use the SERVICE_ROLE_KEY in your backend for this to work.
create policy "Enable all access for service role"
on users
for all
to service_role
using (true)
with check (true);

-- Allow public read access so anyone can resolve an address to a handle
create policy "Enable read access for all users"
on users
for select
using (true);
